language: julia

os:
  - linux

julia:
  - 0.7
  - 1.0

notifications:
  email: false

sudo: false

after_success:
  - julia -e 'Pkg.add("Documenter")'
  - julia -e 'cd(Pkg.dir("MarketData")); include(joinpath("docs", "make.jl"))'
